### PR TITLE
Fix issues with having null values for firstAired and network attributes

### PR DESCRIPTION
**Pull request by DariusIII**
Attributes firstAired and network are sometimes having null values which is causing exceptions to be thrown.

### CODE REVIEW

**Comment by canihavesomecoffee** [comment]
@DariusIII Thanks for the fix 🥇. It's a shame the API is so loose with returning null on almost all fields though...

**Comment by DariusIII** [comment]
@canihavesomecoffee Their v3 API needs a lot of tweaking, as far as i can tell.

**Comment by canihavesomecoffee** [comment]
Feel free to open more PR's if you spot other things I might have missed :)

I've released 1.2.2 with your fix included.

**Comment by DariusIII** [comment]
As i am using your work extensively, as soon as i notice something will do a PR, if you haven't fixed it before me.

**Pull request merged**
